export namespace CONSTS {
    export const KEY_SWITCHES = [
        {
            id: 1,
            japanese: "赤軸",
            english: "Red",
            color: "red",
            type1: "Mechanical",
            type2: "Linear",
            file: "red",
            sample: 3,
        },
        {
            id: 2,
            japanese: "茶軸",
            english: "Brown",
            color: "brown",
            type1: "Mechanical",
            type2: "Tactile",
            file: "brown",
            sample: 3,
        },
        {
            id: 3,
            japanese: "青軸",
            english: "Blue",
            color: "blue",
            type1: "Mechanical",
            type2: "Clicky",
            file: "blue",
            sample: 3,
        },
        {
            id: 4,
            japanese: "東プレ",
            english: "Topre",
            color: "black",
            type1: "Capacitive",
            type2: null,
            file: "topre",
            sample: 3,
        },
        {
            id: 5,
            japanese: "Mac Book",
            english: "Mac Book",
            color: "grey",
            type1: "Butterfly",
            type2: null,
            file: "mac",
            sample: 3,
        },
    ];
}
