// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyFooter: typeof import('./components/MyFooter.vue')['default']
    MyHeader: typeof import('./components/MyHeader.vue')['default']
    Sandbox: typeof import('./components/Sandbox.vue')['default']
    SwitchCard: typeof import('./components/SwitchCard.vue')['default']
    SwitchCardList: typeof import('./components/SwitchCardList.vue')['default']
  }
}

export {}
